/pcd_subsriber:
  ros__parameters:
    continuous_saving: true
    continuous_saving_rate: 0.5
    pointcloud_buffer_size: 128 # in MB
    frame_id: 'map_gyor_0'
    pcd_file_path: '/mnt/bag/test'
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    topic_name: '/lexus3/sensing/lidar/concatenated/pointcloud'
    use_sim_time: false

